version: '3'
services:

  nginx:
    image: zsgsdesign/laravel-nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "80:80" # custom_port:80
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - php-fpm

  php-fpm:
    image: zsgsdesign/laravel-php-oci:latest
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - app-network
    environment:
        - APP_ENV=production
        - APP_DEBUG=false

networks:
  app-network:
    driver: bridge
